// Traducciones revisadas a mano de la descripción de cada activación (código -> texto en español).
// `node traducciones_manuales.mjs` las vuelca en traducciones.json junto al texto original en inglés.
// Las activaciones que no estén aquí las traduce build_index.js de forma automática (MyMemory).
import { readFile, writeFile } from "node:fs/promises";

const SOLICITA = "Se solicita a Copernicus EMS Rapid Mapping";
const ES = {
  EMSR932: `El 15 de septiembre de 2025 a las 13:00 UTC se notificó un incendio activo que afectaba a terreno forestal antropizado en la provincia de Huelva. Se solicitó a Copernicus EMS Rapid Mapping cartografía de emergencia de primera estimación aproximada, extensión del incendio y evaluación de daños.`,
  EMSR925: `En la tarde del 20 de agosto de 2026 se notificó un incendio forestal en la zona de Segorbe, en la provincia de Castellón, cerca del Parque Natural de la Sierra Calderona. El 21 de agosto el incendio seguía activo y en propagación. Se solicitó a Copernicus EMS Rapid Mapping cartografía de emergencia de delimitación del área quemada y evaluación de daños.`,
  EMSR921: `El 10 de agosto, aproximadamente a las 10:00 UTC, un incendio forestal se propagó por la zona. Afectó a la franja de transición entre áreas naturales, agrícolas y de patrimonio cultural, con una superficie quemada estimada de casi 13.000 hectáreas. Se ordenaron evacuaciones preventivas en 18 localidades de los municipios de Las Peñas de Riglos, Bailo, Jaca, Santa Cilia de Jaca, Santa Cruz de la Serós y Caldearenas. El fuego avanzaba por todo el perímetro y seguía fuera de control. Se solicitó a Copernicus EMS Rapid Mapping cartografía de emergencia de delimitación del área quemada y evaluación de daños.`,
  EMSR913: `El 6 de agosto de 2026 se notificó un incendio forestal en la provincia de Huelva, en el oeste de Andalucía. El incendio seguía activo y en propagación. Se solicitó a Copernicus EMS Rapid Mapping cartografía de emergencia de delimitación del área quemada y evaluación de daños.`,
  EMSR908: `El 29 de julio a las 01:07 (CEST) se inició un incendio forestal en el municipio de Fermoselle (Zamora), muy cerca de la frontera entre España y Portugal. En el momento de la activación había superado las 500 hectáreas y seguía activo en nivel 2, afectando a núcleos de población (confinamientos y evacuaciones). También afecta al Espacio Natural Protegido de Arribes del Duero. El fuego podría extenderse a Portugal. ${SOLICITA} cartografía de emergencia de primera estimación aproximada, extensión del incendio y evaluación de daños.`,
  EMSR906: `En la madrugada del 22 de julio, hacia las 5:00 hora local, se declaró un incendio forestal en la localidad de Castropodame, y hacia las 7:00 un segundo incendio en Murias de Ponjos, ambos en la provincia de León. Los dos incendios seguían activos en ese momento, con más de 500 hectáreas quemadas cada uno. Varias carreteras y localidades se vieron afectadas por las llamas y el humo. Se solicitó a Copernicus EMS Rapid Mapping cartografía de emergencia de extensión del incendio y evaluación de daños.`,
  EMSR905: `El 25 de julio de 2026 se inició un fuego hacia las 9:30 cerca de un colegio. Después de que los bomberos controlaran el primer foco, aparecieron varios puntos de ignición nuevos en las inmediaciones, lo que llevó a las autoridades a sospechar que fue intencionado. El fuerte viento avivó aún más las llamas. Las evacuaciones y confinamientos han afectado a 18.000 personas. Los servicios de emergencia enviaron avisos Es-Alert en toda la comarca de la Plana Baixa. Se evacuaron varias localidades, entre ellas la Vilavella, Artana, Eslida, Aín, Alfondeguilla, Tales y Artesa, con un total de 18 municipios afectados. Se han movilizado medios extraordinarios (UME), y permanecen desplegados bomberos, medios aéreos y brigadas provinciales de emergencia, centrados en proteger las zonas urbanas y evitar que el fuego penetre más en el parque natural de la Serra d'Espadà. ${SOLICITA} cartografía de emergencia de primera estimación aproximada, extensión del incendio y evaluación de daños.`,
  EMSR900: `El 20 de julio de 2026 a las 01:07 UTC un incendio forestal afectó al municipio de Brieva, en la provincia de Segovia, y el 22 de julio de 2026 a las 17:54 hora local se inició otro en el municipio de Almorox, en la provincia de Toledo, que se propagó al municipio de Villa del Prado, en la Comunidad de Madrid. Los incendios causaron daños en masas forestales, espacios naturales protegidos, infraestructuras, red viaria y suministro eléctrico y de agua. Se solicitó a Copernicus EMS Rapid Mapping cartografía de emergencia de primera estimación aproximada, extensión del incendio y evaluación de daños.`,
  EMSR898: `El 19 de julio de 2026 a las 22:00 se notificó un incendio forestal en La Mierla, en la Sierra Norte de Guadalajara. El incendio seguía activo y suponía una amenaza importante para las poblaciones locales, infraestructuras críticas, bosques y recursos naturales cercanos. En ese momento las condiciones meteorológicas favorecían su rápida propagación, con posible desplazamiento de población y daños ambientales graves. Se solicitó a Copernicus EMS Rapid Mapping cartografía de emergencia de primera estimación aproximada, extensión del incendio y evaluación de daños, para apoyar la planificación de la emergencia, la gestión táctica y el despliegue estratégico de medios y personal nacionales.`,
  EMSR896: `El 15 de julio de 2026 a las 13:25 UTC se notificó un incendio forestal en la zona de Asín (Aragón). El incendio seguía activo y en propagación, con daños en masas forestales, vegetación natural, edificios e infraestructuras. Se solicitó a Copernicus EMS Rapid Mapping cartografía de emergencia de primera estimación aproximada, extensión del incendio, delimitación y evaluación de daños.`,
  EMSR892: `El 9 de julio de 2026 a las 14:25 se notificó un incendio forestal en la provincia de Almería (Andalucía). Se han evacuado varias zonas habitadas y se han comunicado 11 víctimas mortales. Las extensas masas forestales, los numerosos municipios y los asentamientos dispersos han creado un escenario de interfaz urbano-forestal de alto riesgo para la población. Se solicitó a Copernicus EMS Rapid Mapping cartografía de emergencia de primera estimación aproximada, extensión del incendio y evaluación de daños.`,
  EMSR888: `Un incendio forestal declarado en el municipio de La Bisbal d'Empordà se propagó hacia el sur. Se puso en alerta a siete municipios mediante el sistema ES-Alert, lo que afectó a un total de 12.000 residentes. Se solicitó a Copernicus EMS Rapid Mapping cartografía de emergencia de primera estimación aproximada, extensión del incendio y evaluación de daños.`,
  EMSR887: `El 24 de junio de 2026 a las 21:27 se notificó un incendio forestal en la zona de Congosto, provincia de León (Castilla y León). El incendio sigue activo y en propagación, con daños en masas forestales, vegetación natural y, potencialmente, infraestructuras cercanas. ${SOLICITA} cartografía de emergencia de primera estimación aproximada, extensión del incendio y evaluación de daños.`,
  EMSR885: `El 25 de junio de 2026 a las 11:30 se notificó un incendio forestal en Aragón. Afectó a zonas de interfaz forestal-agrícola, núcleos de población e infraestructuras. Se ordenaron evacuaciones preventivas en Azanuy, Alins y Calasanz, y la localidad de Fonz quedó confinada porque se esperaba que el fuego avanzara hacia ella. Se solicitó a Copernicus EMS Rapid Mapping cartografía de emergencia de extensión del incendio y evaluación de daños.`,
  EMSR881: `El 8 de junio de 2026 a las 11:30 UTC se notificó un incendio forestal en Villanueva de los Castillejos, en la provincia de Huelva (Andalucía). El fuego se propagó, con daños en masas forestales y posiblemente en infraestructuras. Se solicitó a Copernicus EMS Rapid Mapping cartografía de emergencia de extensión del incendio y evaluación de daños.`,
  EMSR861: `El 26 de enero de 2026 a las 18:00 se notificó que la borrasca Kristin había afectado al centro de Portugal (Coímbra, Castelo Branco y Peniche), y se preveía un desbordamiento fluvial en la cuenca del Guadalquivir, en las provincias de Granada, Jaén y Córdoba (Andalucía). El episodio seguía activo y extendiéndose: en el centro de Portugal se habían comunicado daños por el temporal en edificios, infraestructuras, redes de transporte y suministros, y en Andalucía se esperaba que las inundaciones afectaran a edificios e infraestructuras de las llanuras de inundación del Guadalquivir, incluidas zonas urbanas. Se solicitó a Copernicus EMS Rapid Mapping cartografía de emergencia de extensión del temporal y de la inundación y evaluación de daños para análisis posteriores, y para comprender mejor la respuesta de la cuenca del Guadalquivir a este tipo de episodios.`,
  EMSR842: `El 8 de septiembre a las 19:00 se declaró un incendio forestal en Castromil-Hermisende (Zamora), Castilla y León. Se utilizó el producto de gradación de Copernicus EMS Rapid Mapping para evaluar los daños y obtener mapas detallados de la superficie y la vegetación afectadas. El incendio ya estaba controlado.`,
  EMSR837: `Desde la segunda semana de agosto de 2025, varios incendios forestales han afectado al oeste de España, con repercusión en protección civil. La zona incluía varias localidades y ciudades, carreteras principales y líneas de ferrocarril. Se solicitó a Copernicus EMS Rapid Mapping cartografía de emergencia de primera estimación aproximada, extensión del incendio y evaluación de daños.`,
  EMSR826: `El 28 de julio a las 23:10 se inició un incendio forestal en Cuevas del Valle (Ávila), Castilla y León. El incendio quedó controlado el 1 de agosto de 2025. Se necesitan mapas detallados de la superficie y la vegetación afectadas. ${SOLICITA} cartografía de emergencia de evaluación de daños.`,
  EMSR817: `El 18 de julio de 2025 a las 14:10 se inició un incendio forestal en Navaluenga (Ávila), Castilla y León. El fuego se reactivó en varias ocasiones, pero a 23 de julio de 2025 está controlado y no se espera que se reactive. Los productos de esta activación se usarán para evaluar los daños y obtener mayor detalle de la superficie y la vegetación afectadas. ${SOLICITA} cartografía de emergencia de evaluación de daños.`,
  EMSR812: `El 7 de julio de 2025 a las 12:40 se notificó un incendio forestal en Paüls (Ribera d'Ebre). El incendio seguía activo y propagándose por el bosque, con evolución desfavorable y posibles daños en edificios, infraestructuras y masas forestales. Se solicitó a Copernicus EMS Rapid Mapping cartografía de emergencia de primera estimación aproximada, extensión del incendio y evaluación de daños.`,
  EMSR794: `Debido a las lluvias registradas desde el 8 de marzo en la Comunidad de Madrid y en las provincias de Madrid, Toledo y Guadalajara, se han producido situaciones de volumen extraordinario en algunos embalses de la cuenca del Tajo (principalmente Alcorlo, San Juan, Picadas y Cazalegas). Esto ha obligado a sus responsables a realizar maniobras extraordinarias de desembalse con caudales elevados, que han hecho crecer el caudal del río Henares en la provincia de Guadalajara y de los ríos Alberche y Tajo en la de Toledo. El aumento de caudal ha afectado a núcleos de población y explotaciones agrícolas ribereñas, con inundaciones graves de viviendas que han obligado a las autoridades a evacuarlas. ${SOLICITA} cartografía de emergencia de primera estimación aproximada, extensión de la inundación, monitorización y evaluación de daños.`,
  EMSR792: `Lluvias intensas y persistentes afectan a la Comunitat Valenciana desde el 1 de marzo de 2025. Unidas a la saturación del suelo y al mal estado de muchos cauces e infraestructuras, dañados por las inundaciones de finales de octubre de 2024, hacen probable que vuelva a haber inundaciones en la zona. Ya se han comunicado inundaciones en algunos puntos. ${SOLICITA} cartografía de emergencia de extensión de la inundación, monitorización y evaluación de daños.`,
  EMSR773: `El 29 de octubre de 2024 a las 14:30 UTC, un episodio de lluvias extraordinarias afectó a la región de Valencia. Los altos niveles de los ríos causaron inundaciones en la Ribera Alta, l'Horta, la Plana de Utiel y el río Letur. El 31 de octubre de 2024, precipitaciones extraordinarias provocaron inundaciones en la provincia de Castellón. ${SOLICITA} cartografía de emergencia de extensión de la inundación, monitorización y gradación de daños.`,
  EMSR719: `La activación se solicita por un incendio forestal ocurrido el 14 de abril de 2024 a las 12:18. Ha evolucionado rápidamente y ha puesto en peligro núcleos de población y viviendas dispersas. Se ha evacuado a unas 200 personas, dos carreteras siguen cortadas y el fuego afecta a una Zona Especial de Conservación (ZEC). Según los últimos datos, han ardido unas 700 hectáreas. El incendio sigue activo, aunque con evolución favorable. ${SOLICITA} cartografía de emergencia de primera estimación aproximada, extensión del incendio y evaluación de daños.`,
  EMSR704: `El 2 de noviembre de 2023 a las 13:30 se notifica un incendio forestal en la región de Valencia. El incendio sigue activo y se propaga por el fuerte viento, que se espera que continúe en las próximas horas. ${SOLICITA} cartografía de emergencia de extensión del incendio y evaluación de daños.`,
  EMSR694: `Desde el 3 de septiembre a las 17:00, un sistema tormentoso de lento desplazamiento, denominado oficialmente depresión aislada en niveles altos (DANA), ha afectado a España y ha causado lluvias intensas e inundaciones. La Agencia Estatal de Meteorología (AEMET) emitió aviso rojo para Madrid y Toledo. Las autoridades comunicaron numerosas evacuaciones, rescates en zonas inundadas, personas desaparecidas y víctimas mortales. El episodio ya no está activo, pero causó una inundación catastrófica con graves daños humanos y económicos. Continúan la búsqueda de desaparecidos y la evaluación de daños. ${SOLICITA} cartografía de emergencia de evaluación de daños.`,
  EMSR685: `En la tarde-noche del 15 de agosto de 2023 se inició un incendio forestal en la isla de Tenerife (Canarias). El incendio sigue activo y ya ha afectado a los municipios de Arafo y Candelaria, con riesgo de extenderse a otros. ${SOLICITA} cartografía de emergencia de extensión del incendio y evaluación de daños.`,
  EMSR682: `El 4 de agosto de 2023 a las 14:30 UTC se notifica un incendio forestal en Portbou (Girona). El incendio sigue activo y en propagación. Se ha comunicado que arden 435 ha y que podrían verse afectadas 2.500 ha. ${SOLICITA} cartografía de emergencia de primera estimación aproximada, extensión del incendio y evaluación de daños.`,
  EMSR671: `El 15 de julio de 2023 a las 01:00 UTC se notifica un incendio forestal que afecta a terreno forestal, a los límites de zonas urbanas y al Parque Nacional de la Caldera de Taburiente, en el este de La Palma. Se ha evacuado a más de 500 personas. Las condiciones meteorológicas pueden dar lugar a un comportamiento peligroso del fuego en las próximas horas y días. ${SOLICITA} cartografía de emergencia de primera estimación aproximada, monitorización de la extensión del incendio y evaluación de daños.`,
  EMSR667: `El 17 de mayo de 2023 a las 21:44 se notifica un incendio forestal en la provincia de Cáceres. El fuego, que se inició en el municipio de Pinofranqueado, ha quemado ya unas 8.000 ha, y se han evacuado preventivamente varias poblaciones, con unas 700 personas afectadas y unas 200 alojadas en albergues. Hay carreteras cortadas y actúan medios extraordinarios de extinción. ${SOLICITA} cartografía de emergencia de extensión del incendio y evaluación de daños.`,
  EMSR656: `El 23 de marzo de 2023 a las 12:40 UTC se inició un incendio forestal en las provincias de Castellón y Teruel. El incendio sigue activo y ya ha quemado una superficie considerable. Las llamas están cerca de zonas urbanas y se han evacuado varios pueblos. ${SOLICITA} cartografía de emergencia de primera estimación aproximada, extensión del incendio y evaluación de daños.`,
  EMSR599: `Los días 14 y 15 de julio de 2022 se iniciaron grandes incendios forestales en las provincias de Lugo y Ourense (Galicia, noroeste de España). Afectan sobre todo a los municipios de Folgoso do Courel, O Barco de Valdeorras y Carballeda de Valdeorras, cerca del espacio Natura 2000 Ancares-Courel. Debido a las condiciones meteorológicas adversas,…`,
  EMSR597: `Debido a la situación extrema en la que se encuentra la Península Ibérica, el 18 de julio se inició en Ateca (Zaragoza) un incendio que ha arrasado 2.000 hectáreas y que puede quemar más superficie; es una zona con gran cantidad de combustible y alto valor ecológico. Copernicus EMS Rapid Mapping…`,
  EMSR590: `Un incendio iniciado a primera hora de la tarde del 11 de julio afecta al Parque Natural de Las Batuecas-Sierra de Francia, una zona de gran valor ecológico. Ya han ardido unas 4.000 ha. Varios pueblos se han visto afectados y se ha evacuado a unas 600 personas. Medios estatales…`,
  EMSR583: `A 20 de junio, la situación en Aragón sigue siendo de incendios forestales simultáneos que afectan a zonas de alto valor ecológico. Actualmente el foco está en el incendio de Castejón de Tornos (Teruel), que ya ha destruido unas 2.000 ha y puede arder con alta intensidad…`,
  EMSR581: `El 16 de junio de 2022 la situación en Aragón era de incendios forestales simultáneos que afectaban a zonas de alto valor ecológico (Red Natura 2000). El 17 de junio, el incendio de Nonaspe (Zaragoza) ya había destruido unas 1.000 ha y podía arder con alta intensidad. Actualmente…`,
  EMSR580: `El 15 de junio de 2022 se produjeron varios incendios forestales a causa de una tormenta eléctrica en varios municipios de la provincia de Zamora (Castilla y León). El incendio afecta sobre todo a los municipios de Ferreras de Arriba, Riofrío de Aliste y Ferreras de Abajo. Debido a las condiciones meteorológicas adversas…`,
  EMSR579: `Varios incendios forestales iniciados en la noche del 14 al 15 de junio de 2022 afectan a zonas de protección ambiental y patrimonial; se ha evacuado a varias personas de un monasterio. Situación actual: aunque los incendios están estabilizados por el momento, la previsión meteorológica…`,
  EMSR578: `El 16 de junio de 2022, tres incendios forestales en Cataluña redujeron a cenizas unas 1.100 hectáreas de bosque y matorral, mientras una ola de calor llevaba las temperaturas cerca de máximos históricos en la zona. El incendio de Artesa de Segre (Lleida) ha quemado 500 hectáreas de vegetación y…`,
  EMSR569: `Debido a las fuertes lluvias, se prevén inundaciones en la Comunitat Valenciana a partir del 22 de marzo de 2022. Durante la última semana se han registrado lluvias persistentes, que ahora se han intensificado con registros superiores a 200 mm en algunas zonas. Existe riesgo potencial de inundación en…`,
  EMSR512: `El 20 de mayo de 2021 se inició un gran incendio forestal en la isla de Tenerife (Canarias). Afecta sobre todo al municipio de Arico, en el sureste de la isla, y al Parque Natural de la Corona Forestal, junto al Parque Nacional del Teide, donde hay un número importante de endemismos…`,
  EMSR474: `El verano pasado se declaró un gran incendio en las sierras del norte de la provincia de Cáceres, de las que nacen afluentes que vierten sus aguas al río Tiétar. Además, los días 20 y 21 de octubre de 2020 la misma zona recibió lluvias más intensas de lo habitual…`,
  EMSR430: `El 23 de febrero de 2020, en la isla de Tenerife (Canarias), unas condiciones meteorológicas adversas, con vientos de más de 100 km/h, calima intensa y altas temperaturas, provocaron varios incendios en el norte de la isla. Fueron especialmente intensos los del municipio de Santa Úrsula…`,
  EMSR428: `El 22 de febrero de 2020 se inició un incendio en la isla de Gran Canaria, en el municipio de La Aldea, en el suroeste de la isla. A causa del fuego se ha evacuado a doscientas personas de sus casas. Las condiciones meteorológicas, con viento de más de 90-100 km/h…`,
  EMSR425: `El jueves 6 de febrero de 2020 se derrumbó un vertedero cerca de Ermua, en el País Vasco. Han desaparecido dos trabajadores. Por la enorme cantidad de residuos del vertedero, su inestabilidad y el tipo de residuos que contiene, las tareas de búsqueda son muy complejas. Desde el punto de vista de la seguridad…`,
  EMSR422: `A causa de la borrasca Gloria, Cataluña sufre daños extensos por inundaciones y fuertes vientos, que afectan a personas e infraestructuras. Se solicita a Copernicus EMS Rapid Mapping cartografiar la extensión de las inundaciones de los días 23 y 24 de enero de 2020. También se solicita la gradación de daños.`,
  EMSR397: `El actual episodio de lluvias intensas producirá posiblemente crecidas de carácter extraordinario en amplios sectores de la subcuenca del río Segre, con posibles afecciones a núcleos de población, comunicaciones, infraestructuras y otros.`,
  EMSR305: `Desde el 6 de agosto arde un incendio en Valencia. A consecuencia de varios incendios forestales, se evacuó preventivamente de sus casas a unas 2.500 personas mientras los bomberos combatían varios focos. Según la información disponible el 7 de agosto, este incendio ya ha quemado unas 1.500…`,
  EMSR302: `Incendios forestales ocurridos el 2 de agosto de 2018 en Nerva, en Andalucía, suroeste de España. El fuego está actualmente sin control y afecta a una superficie de más de 1.000 ha.`,
  EMSR288: `Incendio forestal ocurrido del 12 al 13 de mayo de 2018 en la zona de Santa Colomba, en la provincia de León, noroeste de España. El gobierno de la región (Junta de Castilla y León) tiene especial interés en el mapa de delimitación y el de gradación de este incendio por su gran extensión y el valor ecológico de…`,
  EMSR279: `Desde el 12 de abril de 2018 se está produciendo una crecida extraordinaria en la cuenca del Ebro a causa de la fusión de la nieve en los Pirineos. Las primeras zonas inundadas se registraron en Castejón (Navarra), y la punta en la ciudad de Zaragoza se prevé para el 15 de abril hacia las 12:00 UTC.`,
  EMSR278: `El 8 de abril de 2018 se inició un incendio forestal en el municipio de Granadilla de Abona, en el sur de Tenerife. El fuerte viento y un terreno abrupto e inhóspito dificultan la extinción. El fuego arde en la zona del Paisaje Lunar, en Vilaflor y Granadilla de Abona, entre la pista de Madre del Agua y…`,
  EMSR259: `Un incendio forestal iniciado el 3 de diciembre en Torre la Ribera (Huesca, Aragón) quema unas 100 ha en un terreno de muy difícil acceso cubierto de pinos y robles. En la emergencia participan numerosos medios autonómicos y estatales.`,
  EMSR254: `Durante octubre de 2017 numerosos incendios forestales afectaron a España, sobre todo en las zonas centrales. La Junta de Castilla y León activó el servicio Copernicus EMS Rapid Mapping para producir mapas de delimitación y gradación de las zonas afectadas con el fin de evaluar los daños en…`,
  EMSR248: `Durante agosto de 2017 numerosos incendios forestales afectaron a España, sobre todo en las zonas centrales. La Junta de Castilla y León activó el servicio Copernicus EMS Rapid Mapping para producir mapas de delimitación y gradación de las zonas afectadas con el fin de evaluar los daños en…`,
  EMSR227: `Un incendio declarado el 22 de agosto en Encinedo (León), en la comarca de La Cabrera, quemó casi 10.000 hectáreas. El interés principal de esta activación es determinar el perímetro real del incendio y evaluar los daños a la vegetación y otros daños ambientales. Los productos se usarán para fijar prioridades de…`,
  EMSR219: `El 3 de agosto de 2017 a las 19:00 (CEST) se inició un incendio forestal en el municipio de Segura de la Sierra (Jaén) que afectó al Parque Natural de Cazorla, Segura y Las Villas. El fuego se ha extendido a otros municipios cercanos, como Orcera.`,
  EMSR216: `En Yeste, en el sureste de España, ardieron en pocos días más de 3.000 hectáreas de un denso pinar de topografía difícil; el incendio afectó a 12 aldeas, de las que se evacuó a más de 500 personas. También preocupan los daños a la vegetación y al medio ambiente.`,
  EMSR211: `El 28 de junio de 2017 se declaró un nuevo incendio forestal en Gátova (Valencia). Como buena parte de España, la zona está en alerta máxima por incendios forestales debido a una ola de calor.`,
  EMSR210: `Hay un nuevo incendio forestal activo en la provincia de Huelva, por el que se evacuó por precaución a casi 400 personas de la zona norte de la localidad de El Campillo.`,
  EMSR209: `Un gran incendio forestal en el sur de España ha obligado a evacuar a más de 1.500 personas de viviendas, campings y hoteles. El fuego comenzó el sábado por la noche en la costa sur y avanzó hacia el este hasta alcanzar el espacio natural de Doñana, uno de los santuarios de fauna más importantes del país…`,
  EMSR132: `El 6 de agosto a las 10:00 se inició un incendio forestal en el municipio de Acebo (Cáceres). El fuego se ha extendido a otros municipios cercanos, Perales del Puerto y Hoyos, y supone un gran peligro para la población. El incendio sigue activo.`,
  EMSR127: `El 5 de julio a las 14:00 se inició un incendio forestal en el municipio de Quesada, en la provincia de Jaén. El fuego se ha extendido a municipios vecinos como Larva y Huesa. El 8 de julio a las 10:00 se inició un segundo incendio forestal en la zona de Lújar, en la provincia de Granada, que alcanzó otros municipios como…`,
  EMSR120: `Las inundaciones en la cuenca del Ebro comenzaron los días 25 y 26 de febrero de 2015, a causa de la fusión de las recientes nevadas en los Pirineos.`,
  EMSR118: `Las fuertes lluvias que comenzaron el 31 de enero de 2015 han causado inundaciones en la cuenca del Ebro que afectan a muchos pueblos de la provincia de Zaragoza.`,
};

const datos = JSON.parse(await readFile(new URL("./data/activaciones.json", import.meta.url), "utf8")).activations;
const salida = new URL("./traducciones.json", import.meta.url);
let tr = {};
try { tr = JSON.parse(await readFile(salida, "utf8")); } catch {}
let n = 0;
for (const a of datos) {
  const en = a.reason || a.summary || "";
  if (en && ES[a.code]) { tr[a.code] = { en, es: ES[a.code], auto: false }; n++; }
}
const sobran = Object.keys(ES).filter(c => !datos.some(a => a.code === c));
await writeFile(salida, JSON.stringify(tr, null, 1));
console.log(`traducciones.json: ${n} traducciones manuales` + (sobran.length ? `; códigos sin activación: ${sobran}` : ""));
console.log("Con texto y sin traducción manual:", datos.filter(a => (a.reason || a.summary) && !ES[a.code]).map(a => a.code).join(" ") || "ninguna");
